/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _IndexRoute } from '../pages/';
import { Route as _LetterDetailRoute } from '../pages/letter-detail';
import { Route as _LettersRoute } from '../pages/letters';
import { Route as _MemorialBookRoute } from '../pages/memorial-book';
import { Route as _NotificationsRoute } from '../pages/notifications';
import { Route as _OnboardingRoute } from '../pages/onboarding';
import { Route as _PetCreateRoute } from '../pages/pet-create';
import { Route as _PetsRoute } from '../pages/pets';
import { Route as _QuestTodayRoute } from '../pages/quest-today';
import { Route as _SettingsRoute } from '../pages/settings';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/': (typeof _IndexRoute)['_inputType'];
    '/letter-detail': (typeof _LetterDetailRoute)['_inputType'];
    '/letters': (typeof _LettersRoute)['_inputType'];
    '/memorial-book': (typeof _MemorialBookRoute)['_inputType'];
    '/notifications': (typeof _NotificationsRoute)['_inputType'];
    '/onboarding': (typeof _OnboardingRoute)['_inputType'];
    '/pet-create': (typeof _PetCreateRoute)['_inputType'];
    '/pets': (typeof _PetsRoute)['_inputType'];
    '/quest-today': (typeof _QuestTodayRoute)['_inputType'];
    '/settings': (typeof _SettingsRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/': (typeof _IndexRoute)['_outputType'];
    '/letter-detail': (typeof _LetterDetailRoute)['_outputType'];
    '/letters': (typeof _LettersRoute)['_outputType'];
    '/memorial-book': (typeof _MemorialBookRoute)['_outputType'];
    '/notifications': (typeof _NotificationsRoute)['_outputType'];
    '/onboarding': (typeof _OnboardingRoute)['_outputType'];
    '/pet-create': (typeof _PetCreateRoute)['_outputType'];
    '/pets': (typeof _PetsRoute)['_outputType'];
    '/quest-today': (typeof _QuestTodayRoute)['_outputType'];
    '/settings': (typeof _SettingsRoute)['_outputType'];
  }
}
